### ISSUE TITLE
Case sensitive regex match in C# uaparser

### ISSUE THREAD

**Issue by sungbonglee** [tobie/ua-parser#517]
Hi,

Before I report a bug, I really appreciate to any body who accomplished this wonderful project.

I was testing different user agent string and I realized that the regex.Match function in C# was not ignoring the letter case. This was giving me problem for example when an user agent string contains the word "iphone" instead of iPhone.
I am not sure if this was design intended, but I think it is better to make the regex case insensitive to parse the user agent strings.

Thanks!

**Comment by enemaerke** [comment]
Hi there.

First of, this project has been moved to a new organization called ua-parser (http://github.com/ua-parser) and split into the core regex's (http://github.com/ua-parser/uap-core) and several language specific implementations. You should really be creating issues within that setup instead of here.

As for you question. Regex case sensitivity is actually controlled on a per-regex basis using a 'regex_flag' in the yaml file (located in http://github.com/ua-parser/uap-core). The C# implementation (located at http://github.com/ua-parser/uap-csharp) respects this flag and will not do a general case insensitive switch on all regex'es. If you feel that the regex'es does not catch all appropriate cases, you should create a PR in the uap-core project, correcting the specific regex so all language implementations will benefit.
